strings = {
	# ui strings
	'mora': "Mora",
	'xp': 'Character Exp',
	'wep_xp': 'Weapon Exp',
	'resin': 'Resin',
	'location': "Location",
	'item': 'Item',
	'item_s': 'Item(s)',
	'character_s': 'Character(s)',
	'characters': 'Characters',
	'inventory': 'Inventory',
	'add': 'Add',
	'character': 'Character',
	'name': 'Name',
	'level': 'Level',
	'now': 'Now',
	'goal': 'Goal',
	'normal': 'Normal',
	'skill': 'Skill',
	'burst': 'Burst',
	'weapon': 'Weapon',
	'artifacts': 'Artifacts',
	'click_to_remove': 'Click to Remove',
	'need': 'Need',
	'have': 'Have',
	'missing_': 'Missing',
	'reset_all_data': 'Reset All Data',
	'reset_character': 'Reset Character',
	'reset_inventory': 'Reset Inventory',
	'convert_notice': '<span class="bad">_Red_</span> means you need that material.<br />'
					  '<span class="convert">_Orange_</span> means you need that material and can convert the previous tier.<br/ >'
					  '<span class="good">_Green_(#)_</span> means you have enough of that material left over to convert up # times.',
	# Weekly Boss Talent Drop
	'tusk_of_monoceros_caeli': "Tusk of Monoceros Caeli",
	'shard_of_a_foul_legacy': "Shard of a Foul Legacy",
	'shadow_of_the_warrior': "Shadow of the Warrior",
	'dvalins_claw': "Dvalin's Claw",
	'dvalins_plume': "Dvalin's Plume",
	'dvalins_sigh': "Dvalin's Sigh",
	'ring_of_boreas': 'Ring of Boreas',
	'spirit_locket_of_boreas': 'Spirit Locket of Boreas',
	'tail_of_boreas': 'Tail of Boreas',
	# Characters
	'amber': 'Amber',
	'barbara': 'Barbara',
	'beidou': 'Beidou',
	'bennett': 'Bennett',
	'chongyun': 'Chongyun',
	'diluc': 'Diluc',
	'fischl': 'Fischl',
	'jean': 'Jean',
	'kaeya': 'Kaeya',
	'keqing': 'Keqing',
	'klee': 'Klee',
	'lisa': 'Lisa',
	'mona': 'Mona',
	'ningguang': 'Ningguang',
	'noelle': 'Noelle',
	'qiqi': 'Qiqi',
	'razor': 'Razor',
	'sucrose': 'Sucrose',
	'venti': 'Venti',
	'xiangling': 'Xiangling',
	'xingqiu': 'Xingqiu',
	'tartaglia': 'Tartaglia',
	'diona': 'Diona',
	'traveler': "Traveler",
	'traveler_pyro': "Traveler (Pyro)",
	'traveler_hydro': "Traveler (Hydro)",
	'traveler_electro': "Traveler (Electro)",
	'traveler_geo': "Traveler (Geo)",
	'traveler_anemo': "Traveler (Anemo)",
	'traveler_cryo': "Traveler (Cryo)",
	# Character Ascention materials 1
	'agnidus_agate': ['Agnidus Agate Sliver', 'Agnidus Agate Fragment', 'Agnidus Agate Chunk', 'Agnidus Agate Gemstone'],
	'brilliant_diamond': ['Brilliant Diamond Sliver', 'Brilliant Diamond Fragment', 'Brilliant Diamond Chunk', 'Brilliant Diamond Gemstone'],
	'prithiva_topaz': ['Prithiva Topaz Sliver', 'Prithiva Topaz Fragment', 'Prithiva Topaz Chunk', 'Prithiva Topaz Gemstone'],
	'shivada_jade': ['Shivada Jade Sliver', 'Shivada Jade Fragment', 'Shivada Jade Chunk', 'Shivada Jade Gemstone'],
	'vajrada_amethyst': ['Vajrada Amethyst Sliver', 'Vajrada Amethyst Fragment', 'Vajrada Amethyst Chunk', 'Vajrada Amethyst Gemstone'],
	'varunada_lazurite': ['Varunada Lazurite Sliver', 'Varunada Lazurite Fragment', 'Varunada Lazurite Chunk', 'Varunada Lazurite Gemstone'],
	'vayuda_turqoise': ['Vayuda Turquoise Sliver', 'Vayuda Turquoise Fragment', 'Vayuda Turquoise Chunk', 'Vayuda Turquoise Gemstone'],
	# character ascension materials 2
	'basalt_pillar': 'Basalt Pillar',
	'cleansing_heart': 'Cleansing Heart',
	'everflame_seed': 'Everflame Seed',
	'hoarfrost_core': 'Hoarfrost Core',
	'hurricane_seed': 'Hurricane Seed',
	'lightning_prism': 'Lightning Prism',
	# common gathered items
	'calla_lily': 'Calla Lily',
	'cecilia': 'Cecilia',
	'cor_lapis': 'Cor Lapis',
	'dandelion_seed': 'Dandelion Seed',
	'glaze_lilly': 'Glaze Lily',
	'jueyun_chili': 'Jueyun Chili',
	'noctilucous_jade': 'Noctilucous Jade',
	'philanemo_mushroom': 'Philanemo Mushroom',
	'silk_flower': 'Silk Flower',
	'small_lamp_grass': 'Small Lamp Grass',
	'starconch': 'Starconch',
	'valberry': 'Valberry',
	'violetgrass': 'Violetgrass',
	'windwheel_aster': 'Windwheel Aster',
	'wolfhook': 'Wolfhook',
	# common enemy drops
	'arrowhead': ['Firm Arrowhead', 'Sharp Arrowhead', 'Weathered Arrowhead'],
	'f_insignia': ["Recruit's Insignia", "Sergeant's Insignia", "Lieutenant's Insignia"],
	'th_insignia': ["Treasure Hoarder Insignia", "Silver Raven Insignia", "Golden Raven Insignia"],
	'mask': ['Damaged Mask', 'Stained Mask', 'Ominous Mask'],
	'nectar': ['Whopperflower Nectar', 'Shimmering Nectar', 'Energy Nectar'],
	'scroll': ['Divining Scroll', 'Sealed Scroll', 'Forbidden Curse Scroll'],
	'slime': ['Slime Condensate', 'Slime Secretions', 'Slime Concentrate'],
	# boss enemy drops
	'bone_shard': ["Fragile Bone Shard", "Sturdy Bone Shard", "Fossilized Bone Shard"],
	'chaos': ["Chaos Device", "Chaos Circuit", "Chaos Core"],
	'horn': ["Heavy Horn", "Black Copper Horn", "Black Crystal Horn"],
	'ley_line': ["Dead Ley Line Branches", "Dead Ley Line Leaves", "Ley Line Sprouts"],
	'mist': ["Mist Flower Pollen", "Mist Grass", "Mist Grass Lamp"],
	'sacrificial_knife': ["Hunter's Sacrificial Knife", "Agent's Sacrificial Knife", "Inspector's Sacrificial Knife"],
	# domain weapon ascension materials
	'aerosiderite': ["Grain of Aerosiderite", "Piece of Aerosiderite", "Bit of Aerosiderite", "Chunk of Aerosiderite"],
	'boreal_wolf': ["Boreal Wolf's Milk Tooth", "Boreal Wolf's Cracked Tooth", "Boreal Wolf's Broken Fang", "Boreal Wolf's Nostalgia"],
	'dandelion_gladiator': ["Fetters of the Dandelion Gladiator", "Chains of the Dandelion Gladiator", "Shackles of the Dandelion Gladiator", "Dream of the Dandelion Gladiator"],
	'decarabian': ["Tile of Decarabian's Tower", "Debris of Decarabian's City", "Fragment of Decarabian's Epic", "Scattered Piece of Decarabian's Dream"],
	'guyun': ["Luminous Sands from Guyun", "Lustrous Stone from Guyun", "Relic from Guyun", "Divine Body from Guyun"],
	'mist_veiled_elixer': ["Mist Veiled Lead Elixir", "Mist Veiled Mercury Elixir", "Mist Veiled Gold Elixir", "Mist Veiled Primo Elixir"],
	# domain talent materials
	'ballad': ['Teachings of "Ballad"', 'Guide to "Ballad"', 'Philosophies of "Ballad"'],
	'diligence': ['Teachings of "Diligence"', 'Guide to "Diligence"', 'Philosophies of "Diligence"'],
	'freedom': ['Teachings of "Freedom"', 'Guide to "Freedom"', 'Philosophies of "Freedom"'],
	'gold': ['Teachings of "Gold"', 'Guide to "Gold"', 'Philosophies of "Gold"'],
	'prosperity': ['Teachings of "Prosperity"', 'Guide to "Prosperity"', 'Philosophies of "Prosperity"'],
	'resistance': ['Teachings of "Resistance"', 'Guide to "Resistance"', 'Philosophies of "Resistance"'],
	'crown': 'Crown of Sagehood',
	# bows
	'alley_hunter': 'Alley Hunter',
	'amos_bow': "Amos' Bow",
	'blackcliff_warbow': 'Blackcliff Warbow',
	'compound_bow': 'Compound Bow',
	'ebony_bow': 'Ebony Bow',
	'favonius_warbow': 'Favonius Warbow',
	'messenger': 'Messenger',
	'prototype_crescent': 'Prototype Crescent',
	'raven_bow': 'Raven Bow',
	'recurve_bow': 'Recurve Bow',
	'royal_bow': 'Royal Bow',
	'rust': 'Rust',
	'sacrificial_bow': 'Sacrificial Bow',
	'sharpshooters_oath': "Sharpshooter's Oath",
	'skyward_harp': 'Skyward Harp',
	'slingshot': 'Slingshot',
	'the_stringless': 'The Stringless',
	'the_viridescent_hunt': 'The Viridescent Hunt',
	# catalysts
	'amber_catalyst': 'Amber Catalyst',
	'blackcliff_amulet': 'Blackcliff Amulet',
	'emerald_orb': 'Emerald Orb',
	'eye_of_perception': 'Eye of Perception',
	'favonius_codex': 'Favonius Codex',
	'lost_prayer_to_the_sacred_winds': 'Lost Prayer to the Sacred Winds',
	'magic_guide': 'Magic Guide',
	'mappa_mare': 'Mappa Mare',
	'otherworldly_story': 'Otherworldly Story',
	'prototype_malice': 'Prototype Malice',
	'royal_grimoire': 'Royal Grimoire',
	'sacrificial_fragments': 'Sacrificial Fragments',
	'skyward_atlas': 'Skyward Atlas',
	'solar_pearl': 'Solar Pearl',
	'the_widsith': 'The Widsith',
	'thrilling_tales_of_dragon_slayers': 'Thrilling Tales of Dragon Slayers',
	'twin_nephrite': 'Twin Nephrite',
	'wine_and_song': 'Wine and Song',
	'memory_of_dust': 'Memory of Dust',
	# Claymores
	'blackcliff_slasher': 'Blackcliff Slasher',
	'bloodtainted_greatsword': 'Bloodtainted Greatsword',
	'debate_club': 'Debate Club',
	'favonius_greatsword': 'Favonius Greatsword',
	'ferrous_shadow': 'Ferrous Shadow',
	'lithic_blade': 'Lithic Blade',
	'prototype_aminus': 'Prototype Aminus',
	'quartz': 'Quartz',
	'rainslasher': 'Rainslasher',
	'royal_greatsword': 'Royal Greatsword',
	'sacrificial_greatsword': 'Sacrificial Greatsword',
	'serpent_spine': 'Serpent Spine',
	'skyrider_greatsword': 'Skyrider Greatsword',
	'skyward_pride': 'Skyward Pride',
	'the_bell': 'The Bell',
	'white_iron_greatsword': 'White Iron Greatsword',
	'whiteblind': 'Whiteblind',
	'wolfs_gravestone': "Wolf's Gravestone",
	'the_unforged': 'The Unforged',
	# Polearms
	'black_tassel': 'Black Tassel',
	'blackcliff_pole': 'Blackcliff Pole',
	'crescent_pike': 'Crescent Pike',
	'deathmatch': 'Deathmatch',
	'dragons_bane': "Dragon's Bane",
	'favonius_lance': 'Favonius Lance',
	'halberd': 'Halberd',
	'kunwus_iris_rift': "Kunwu's Iris Rift",
	'lithic_spear': 'Lithic Spear',
	'primordial_jade_winged-spear': 'Primordial Jade Winged-Spear',
	'prototype_grudge': 'Prototype Grudge',
	'skyward_spine': 'Skyward Spine',
	'white_tassel': 'White Tassel',
	'vortex_vanquisher': 'Vortex Vanquisher',
	'royal_spear': 'Royal Spear',
	# Swords
	'aquila_favonia': 'Aquila Favonia',
	'blackcliff_longsword': 'Blackcliff Longsword',
	'cool_steel': 'Cool Steel',
	'dark_iron_sword': 'Dark Iron Sword',
	'favonius_sword': 'Favonius Sword',
	'fillet_blade': 'Fillet Blade',
	'harbinger_of_dawn': 'Harbinger of Dawn',
	'iron_sting': 'Iron Sting',
	'lions_roar': "Lion's Roar",
	'prototype_rancour': 'Prototype Rancour',
	'royal_longsword': 'Royal Longsword',
	'sacrificial_sword': 'Sacrificial Sword',
	'skyrider_sword': 'Skyrider Sword',
	'skyward_blade': 'Skyward Blade',
	'sword_of_descension': 'Sword of Descension',
	'the_alley_flash': 'The Alley Flash',
	'the_black_sword': 'The Black Sword',
	'the_flute': 'The Flute',
	'travelers_handy_sword': "Traveler's Handy Sword",
	# Artifacts
	'adventurer': "Adventurer",
	'archaic_petra': "Archaic Petra",
	'berserker': "Berserker",
	'bloodstained_chivalry': "Bloodstained Chivalry",
	'brave_heart': "Brave Heart",
	'crimson_witch_of_flames': "Crimson Witch of Flames",
	'defenders_will': "Defender's Will",
	'gambler': "Gambler",
	'gladiators_finale': "Gladiator's Finale",
	'instructor': "Instructor",
	'lavawalker': "Lavawalker",
	'lucky_dog': "Lucky Dog",
	'maiden_beloved': "Maiden Beloved",
	'martial_artist': "Martial Artist",
	'noblesse_oblige': "Noblesse Oblige",
	'prayers_for_destiny': "Prayers for Destiny",
	'prayers_for_illumination': "Prayers for Illumination",
	'prayers_for_wisdom': "Prayers for Wisdom",
	'prayers_to_springtime': "Prayers to Springtime",
	'resolution_of_sojourner': "Resolution of Sojourner",
	'retracing_bolide': "Retracing Bolide",
	'scholar': "Scholar",
	'the_exile': "The Exile",
	'thundering_fury': "Thundering Fury",
	'thundersoother': "Thundersoother",
	'tiny_miracle': "Tiny Miracle",
	'traveling_doctor': "Traveling Doctor",
	'viridescent_venerer': "Viridescent Venerer",
	'wanderers_troupe': "Wanderer's Troupe",
	# Days of the Week
	'any': 'Any Day',
	'mon': 'Monday',
	'tue': 'Tuesday',
	'wed': 'Wednesday',
	'thu': 'Thursday',
	'fri': 'Friday',
	'sat': 'Saturday',
	'sun': 'Sunday',
	# general gameplay
	'adventure_rank': "Adventure Rank Reward",
	'special_liyue': "Found around Liyue",
	'special_mondstadt': "Found around Mondstadt",
	'event': 'Event item',
	'xp_leyline': 'Exp Leyline',
	'blacksmith': 'Blacksmith (Refine Ore)',
	'mora_leyline': 'Mora Leyline',
	# common mobs
	'hilichurl': "Melee Hilichurls",
	'ranged_hilichurl': "Ranged Hilichurls",
	'samachurl': "Hilichurl Casters",
	'slimes': "Slimes",
	'treasure_hoarder': "Treasure Hoarders",
	# bosses
	'bosses': "World (Bosses)",
	'abyss_mage': "Abyss Mage",
	'agent': "Fatui Agent",
	'electro_cicin_mage': "Electro Cicin Mage",
	'geovishap_hatchling': "Geovishap Hatchling",
	'mitachurl': "Mitachurl",
	'ruin_guard': "Ruin Guard or Hunter",
	'skirmisher': "Fatui Skirmisher",
	'whopperflower': "Whopperflower",
	# elite bosses
	'anemo_hypostasis': "Anemo Hypostasis",
	'cryo_regisvine': "Cryo Regisvine",
	'electro_hypostasis': "Electro Hypostasis",
	'geo_hypostasis': "Geo Hypostasis",
	'oceanid': "Oceanid",
	'pyro_regisvine': "Pyro Regisvine",
	'40_boss': "Any 40 Resin Boss",
	# weekly boss
	'stormterror': "Stormterror",
	'wolf_of_the_north': "Wolf of the North",
	'golden_house': "Golden House",
	'60_boss': "Any Weekly Boss",
	# Domain: Weapon Ascension Materials
	'cecilia_garden': "Cecilia Garden",
	'hidden_palace_of_lianshan_formula': "Hidden Palace of Lianshan Formula",
	# Domain: Talent Materials
	'forsaken_rift': "Forsaken Rift",
	'taishan_mansion': "Taishan Mansion",
	# Domain: Artifacts
	'clear_pool_and_mountain_cavern': "Clear Pool and Mountain Cavern",
	'domain_of_guyun': "Domain of Guyun",
	'hidden_palace_of_zhou_formula': "Hidden Palace of Zhou Formula",
	'midsummer_courtyard': "Midsummer Courtyard",
	'valley_of_remembrance': "Valley of Remembrance",
}
