weapons = {
	'bow': {
		'amos_bow': {'wam': 'dandelion_gladiator', 'common_rare': 'chaos', 'common': 'slime', 'tier': '5_weapon'},
		'skyward_harp': {'wam': 'boreal_wolf', 'common_rare': 'ley_line', 'common': 'arrowhead', 'tier': '5_weapon'},
		'compound_bow': {'wam': 'aerosiderite', 'common_rare': 'bone_shard', 'common': 'f_insignia', 'tier': '4_weapon'},
		'blackcliff_warbow': {'wam': 'guyun', 'common_rare': 'sacrificial_knife', 'common': 'th_insignia', 'tier': '4_weapon'},
		'the_viridescent_hunt': {'wam': 'decarabian', 'common_rare': 'horn', 'common': 'arrowhead', 'tier': '4_weapon'},
		'prototype_crescent': {'wam': 'mist_veiled_elixer', 'common_rare': 'mist', 'common': 'th_insignia', 'tier': '4_weapon'},
		'sacrificial_bow': {'wam': 'boreal_wolf', 'common_rare': 'ley_line', 'common': 'slime', 'tier': '4_weapon'},
		'alley_hunter': {'wam': 'boreal_wolf', 'common_rare': 'ley_line', 'common': 'th_insignia', 'tier': '4_weapon'},
		'rust': {'wam': 'guyun', 'common_rare': 'sacrificial_knife', 'common': 'mask', 'tier': '4_weapon'},
		'the_stringless': {'wam': 'decarabian', 'common_rare': 'horn', 'common': 'arrowhead', 'tier': '4_weapon'},
		'royal_bow': {'wam': 'dandelion_gladiator', 'common_rare': 'chaos', 'common': 'scroll', 'tier': '4_weapon'},
		'favonius_warbow': {'wam': 'dandelion_gladiator', 'common_rare': 'chaos', 'common': 'nectar', 'tier': '4_weapon'},
		'sharpshooters_oath': {'wam': 'boreal_wolf', 'common_rare': 'ley_line', 'common': 'slime', 'tier': '3_weapon'},
		'slingshot': {'wam': 'guyun', 'common_rare': 'sacrificial_knife', 'common': 'mask', 'tier': '3_weapon'},
		'raven_bow': {'wam': 'decarabian', 'common_rare': 'horn', 'common': 'arrowhead', 'tier': '3_weapon'},
		'messenger': {'wam': 'mist_veiled_elixer', 'common_rare': 'mist', 'common': 'th_insignia', 'tier': '3_weapon'},
		'recurve_bow': {'wam': 'dandelion_gladiator', 'common_rare': 'chaos', 'common': 'scroll', 'tier': '3_weapon'},
	},
	'catalyst': {
		'memory_of_dust': {'wam': 'aerosiderite', 'common_rare': 'bone_shard', 'common': 'mask', 'tier': '5_weapon'},
		'skyward_atlas': {'wam': 'boreal_wolf', 'common_rare': 'ley_line', 'common': 'arrowhead', 'tier': '5_weapon'},
		'lost_prayer_to_the_sacred_winds': {'wam': 'dandelion_gladiator', 'common_rare': 'chaos', 'common': 'slime', 'tier': '5_weapon'},
		'eye_of_perception': {'wam': 'mist_veiled_elixer', 'common_rare': 'mist', 'common': 'mask', 'tier': '4_weapon'},
		'blackcliff_amulet': {'wam': 'guyun', 'common_rare': 'sacrificial_knife', 'common': 'scroll', 'tier': '4_weapon'},
		'favonius_codex': {'wam': 'decarabian', 'common_rare': 'horn', 'common': 'scroll', 'tier': '4_weapon'},
		'mappa_mare': {'wam': 'aerosiderite', 'common_rare': 'bone_shard', 'common': 'slime', 'tier': '4_weapon'},
		'prototype_malice': {'wam': 'mist_veiled_elixer', 'common_rare': 'mist', 'common': 'arrowhead', 'tier': '4_weapon'},
		'royal_grimoire': {'wam': 'decarabian', 'common_rare': 'horn', 'common': 'f_insignia', 'tier': '4_weapon'},
		'sacrificial_fragments': {'wam': 'dandelion_gladiator', 'common_rare': 'chaos', 'common': 'th_insignia', 'tier': '4_weapon'},
		'solar_pearl': {'wam': 'guyun', 'common_rare': 'sacrificial_knife', 'common': 'nectar', 'tier': '4_weapon'},
		'the_widsith': {'wam': 'boreal_wolf', 'common_rare': 'ley_line', 'common': 'mask', 'tier': '4_weapon'},
		'wine_and_song': {'wam': 'boreal_wolf', 'common_rare': 'ley_line', 'common': 'scroll', 'tier': '4_weapon'},
		'frostbearer': {'wam': 'dandelion_gladiator', 'common_rare': 'chaos', 'common': 'nectar', 'tier': '4_weapon'},
		'twin_nephrite': {'wam': 'mist_veiled_elixer', 'common_rare': 'mist', 'common': 'f_insignia', 'tier': '3_weapon'},
		'thrilling_tales_of_dragon_slayers': {'wam': 'boreal_wolf', 'common_rare': 'ley_line', 'common': 'scroll', 'tier': '3_weapon'},
		'magic_guide': {'wam': 'decarabian', 'common_rare': 'horn', 'common': 'slime', 'tier': '3_weapon'},
		'emerald_orb': {'wam': 'guyun', 'common_rare': 'sacrificial_knife', 'common': 'th_insignia', 'tier': '3_weapon'},
		'otherworldly_story': {'wam': 'dandelion_gladiator', 'common_rare': 'chaos', 'common': 'mask', 'tier': '3_weapon'},
	},
	'claymore': {
		'the_unforged': {'wam': 'mist_veiled_elixer', 'common_rare': 'mist', 'common': 'th_insignia', 'tier': '5_weapon'},
		'skyward_pride': {'wam': 'boreal_wolf', 'common_rare': 'ley_line', 'common': 'slime', 'tier': '5_weapon'},
		'wolfs_gravestone': {'wam': 'dandelion_gladiator', 'common_rare': 'chaos', 'common': 'scroll', 'tier': '5_weapon'},
		'sacrificial_greatsword': {'wam': 'boreal_wolf', 'common_rare': 'ley_line', 'common': 'arrowhead', 'tier': '4_weapon'},
		'the_bell': {'wam': 'decarabian', 'common_rare': 'horn', 'common': 'nectar', 'tier': '4_weapon'},
		'blackcliff_slasher': {'wam': 'mist_veiled_elixer', 'common_rare': 'mist', 'common': 'f_insignia', 'tier': '4_weapon'},
		'serpent_spine': {'wam': 'aerosiderite', 'common_rare': 'bone_shard', 'common': 'nectar', 'tier': '4_weapon'},
		'whiteblind': {'wam': 'guyun', 'common_rare': 'sacrificial_knife', 'common': 'th_insignia', 'tier': '4_weapon'},
		'royal_greatsword': {'wam': 'dandelion_gladiator', 'common_rare': 'chaos', 'common': 'slime', 'tier': '4_weapon'},
		'rainslasher': {'wam': 'mist_veiled_elixer', 'common_rare': 'mist', 'common': 'scroll', 'tier': '4_weapon'},
		'prototype_aminus': {'wam': 'aerosiderite', 'common_rare': 'bone_shard', 'common': 'mask', 'tier': '4_weapon'},
		'favonius_greatsword': {'wam': 'dandelion_gladiator', 'common_rare': 'chaos', 'common': 'f_insignia', 'tier': '4_weapon'},
		'snow_tombed_starsliver': {'wam': 'decarabian', 'common_rare': 'horn', 'common': 'slime', 'tier': '4_weapon'},
		'skyrider_greatsword': {'wam': 'aerosiderite', 'common_rare': 'bone_shard', 'common': 'th_insignia', 'tier': '3_weapon'},
		'white_iron_greatsword': {'wam': 'dandelion_gladiator', 'common_rare': 'chaos', 'common': 'slime', 'tier': '3_weapon'},
		'ferrous_shadow': {'wam': 'decarabian', 'common_rare': 'horn', 'common': 'nectar', 'tier': '3_weapon'},
		'debate_club': {'wam': 'mist_veiled_elixer', 'common_rare': 'mist', 'common': 'mask', 'tier': '3_weapon'},
		'bloodtainted_greatsword': {'wam': 'boreal_wolf', 'common_rare': 'ley_line', 'common': 'arrowhead', 'tier': '3_weapon'},
	},
	'polearm': {
		'vortex_vanquisher': {'wam': 'aerosiderite', 'common_rare': 'bone_shard', 'common': 'th_insignia', 'tier': '5_weapon'},
		'primordial_jade_winged_spear': {'wam': 'guyun', 'common_rare': 'sacrificial_knife', 'common': 'f_insignia', 'tier': '5_weapon'},
		'skyward_spine': {'wam': 'dandelion_gladiator', 'common_rare': 'chaos', 'common': 'scroll', 'tier': '5_weapon'},
		'royal_spear': {'wam': 'mist_veiled_elixer', 'common_rare': 'mist', 'common': 'f_insignia', 'tier': '4_weapon'},
		'crescent_pike': {'wam': 'guyun', 'common_rare': 'sacrificial_knife', 'common': 'th_insignia', 'tier': '4_weapon'},
		'blackcliff_pole': {'wam': 'mist_veiled_elixer', 'common_rare': 'mist', 'common': 'f_insignia', 'tier': '4_weapon'},
		'dragons_bane': {'wam': 'mist_veiled_elixer', 'common_rare': 'mist', 'common': 'scroll', 'tier': '4_weapon'},
		'prototype_grudge': {'wam': 'aerosiderite', 'common_rare': 'bone_shard', 'common': 'mask', 'tier': '4_weapon'},
		'deathmatch': {'wam': 'boreal_wolf', 'common_rare': 'ley_line', 'common': 'nectar', 'tier': '4_weapon'},
		'favonius_lance': {'wam': 'dandelion_gladiator', 'common_rare': 'chaos', 'common': 'slime', 'tier': '4_weapon'},
		'dragonspine_spear': {'wam': 'boreal_wolf', 'common_rare': 'mist', 'common': 'f_insignia', 'tier': '4_weapon'},
		'black_tassel': {'wam': 'aerosiderite', 'common_rare': 'bone_shard', 'common': 'arrowhead', 'tier': '3_weapon'},
		'white_tassel': {'wam': 'guyun', 'common_rare': 'sacrificial_knife', 'common': 'f_insignia', 'tier': '3_weapon'},
		'halberd': {'wam': 'mist_veiled_elixer', 'common_rare': 'mist', 'common': 'nectar', 'tier': '3_weapon'},
	},
	'sword': {
		'skyward_blade': {'wam': 'boreal_wolf', 'common_rare': 'ley_line', 'common': 'slime', 'tier': '5_weapon'},
		'aquila_favonia': {'wam': 'decarabian', 'common_rare': 'horn', 'common': 'arrowhead', 'tier': '5_weapon'},
		'summit_shaper': {'wam': 'guyun', 'common_rare': 'sacrificial_knife', 'common': 'mask', 'tier': '5_weapon'},
		'blackcliff_longsword': {'wam': 'guyun', 'common_rare': 'sacrificial_knife', 'common': 'arrowhead', 'tier': '4_weapon'},
		'royal_longsword': {'wam': 'decarabian', 'common_rare': 'horn', 'common': 'arrowhead', 'tier': '4_weapon'},
		'favonius_sword': {'wam': 'decarabian', 'common_rare': 'horn', 'common': 'arrowhead', 'tier': '4_weapon'},
		'the_black_sword': {'wam': 'boreal_wolf', 'common_rare': 'ley_line', 'common': 'slime', 'tier': '4_weapon'},
		'the_flute': {'wam': 'boreal_wolf', 'common_rare': 'ley_line', 'common': 'slime', 'tier': '4_weapon'},
		'sacrificial_sword': {'wam': 'dandelion_gladiator', 'common_rare': 'chaos', 'common': 'scroll', 'tier': '4_weapon'},
		'prototype_rancour': {'wam': 'mist_veiled_elixer', 'common_rare': 'mist', 'common': 'f_insignia', 'tier': '4_weapon'},
		'lions_roar': {'wam': 'guyun', 'common_rare': 'sacrificial_knife', 'common': 'th_insignia', 'tier': '4_weapon'},
		'iron_sting': {'wam': 'aerosiderite', 'common_rare': 'bone_shard', 'common': 'nectar', 'tier': '4_weapon'},
		'sword_of_descension': {'wam': 'boreal_wolf', 'common_rare': 'ley_line', 'common': 'th_insignia', 'tier': '4_weapon'},
		'festering_desire': {'wam': 'dandelion_gladiator', 'common_rare': 'horn', 'common': 'f_insignia', 'tier': '4_weapon'},
		'skyrider_sword': {'wam': 'aerosiderite', 'common_rare': 'bone_shard', 'common': 'f_insignia', 'tier': '3_weapon'},
		'fillet_blade': {'wam': 'mist_veiled_elixer', 'common_rare': 'mist', 'common': 'th_insignia', 'tier': '3_weapon'},
		'travelers_handy_sword': {'wam': 'dandelion_gladiator', 'common_rare': 'chaos', 'common': 'scroll', 'tier': '3_weapon'},
		'harbinger_of_dawn': {'wam': 'boreal_wolf', 'common_rare': 'ley_line', 'common': 'slime', 'tier': '3_weapon'},
		'dark_iron_sword': {'wam': 'guyun', 'common_rare': 'sacrificial_knife', 'common': 'mask', 'tier': '3_weapon'},
		'cool_steel': {'wam': 'decarabian', 'common_rare': 'horn', 'common': 'arrowhead', 'tier': '3_weapon'},
	},
}
